language: java

jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
    - 1.0.x

before_install: "npm install -g grunt-cli bower@1.3.9"

script: "mvn verify -X"
